### ISSUE TITLE
Bug: pageProps doesn't  pass into Component when custom _app.js

### ISSUE THREAD

**Issue by nghiepdev** [FormidableLabs/next-urql#36] opened 2020-02-18 09:08 UTC
Hi guys, 

I have an example:
```tsx
// pages/index.tsx
const Home: React.FC = () => (
  <div>
    <Head>
      <title>Home</title>
      <link rel="icon" href="/favicon.ico" />
    </Head>

    {/* <PokémonList /> */}
  </div>
);

// @ts-ignore
Home.getInitialProps = () => {
  return { test: 'test value' };
};

export default Home;
```
and 
```tsx
// pages/_app.tsx
import React from 'react';
import { withUrqlClient } from 'next-urql';
import { AppPropsType } from 'next/dist/next-server/lib/utils';

const App: React.FC<AppPropsType> = ({ Component, pageProps }) => {
  console.log(pageProps); // <== BUG HERE, should be return {test: 'test value'}

  return <Component {...pageProps} />;
};

export default App;
// export default withUrqlClient({ url: 'https://graphql-pokemon.now.sh' })(App);
```

The ```console.log(pageProps) ``` always return `undefined` if I used custom with `withUrqlClient`.

**Comment by parkerziegler** [comment] 2020-02-18 18:14
@nghiepit this seems like it might be a duplicate of: https://github.com/FormidableLabs/next-urql/issues/35 However, I am adding in some additional code to help ensure this is a bit clearer and more seamless. Hoping to release 0.3.0 later today, so when that release gets out I'll ping you here to test.

**Comment by parkerziegler** [comment] 2020-02-19 04:52
So looking at this a bit more closely, it has to do with how `pageProps` gets returned differently when wrapping an `_app.js` component with an HoC and a standard page component with an HoC. TL;DR – Next gives `_app.js` a signature of `({ Component, pageProps })` while all other page components just get `(props)`. I think our HoC just needs to be smarter about where it places those props. In fact, I'm thinking to keep things easier to understand we may want `withUrqlClientPage` and `withUrqlClientApp` HoCs that are optimized for each case ✅

**Closed as completed** 2020-02-21 00:41 UTC

**Comment by jgoux** [comment] 2020-02-24 09:22
Hi, this doesn't seem solved to me : 

```tsx
import { AppProps } from "next/app";
import { FC, useEffect } from "react";
import "typeface-roboto";
import { App } from "~/components/ui/App";
import withUrql from "../lib/urql";

const NextApp: FC<AppProps> = ({ Component, pageProps }) => {
  console.log(pageProps); // undefined
  useEffect(() => {
    const jssStyles = document.querySelector("#jss-server-side");
    if (jssStyles) {
      jssStyles.parentElement?.removeChild(jssStyles);
    }
  }, []);

  return (
    <App>
      <Component {...pageProps} />
    </App>
  );
};

export default withUrql(NextApp);
```

pageProps still logs "undefined" on all my pages that use urql. And the queries are triggered client-side. I'm using the 0.3.0 version of next-urql, it used to work before.
